EMAIL:
 Smtp_Server: smtp.mxhichina.com
 Smtp_Sender : test@tenez.com
 Password : Password
 OnLine_Receiver : techtest@tenez.com
 Pre_Receiver : tester@tenez.com
 Test_Receiver : tester@tenez.com
 Msg_Title : 未名企鹅API自动化测试报告
 Content_Type : application/octet-stream
 Content_Disposition : attachment; filename:"APITestReport.html"
 Text_description : API用例执行情况
 resultPath : html/body/div[1]/p[4]
 on-off : on


DB:
  host : localhost
  username : myself
  password : skyyj
  port : 3306
  database : mystudy


